---
title: 'ITE_cp_model'
author: 'Chunliang Feng (SCNU)'
date: June, 12, 2023
output:
  html_document:
    code_folding: hide
---
```{r setup, include=FALSE}
#rm(list=ls())
require('knitr') 
opts_chunk$set(tidy = FALSE, warning = FALSE, message = FALSE, cache = FALSE)

#load libraries and functions
suppressMessages(library('tidyverse')) # to organize data
suppressMessages(library('rstan')) # for model fiting, using the sampling function
rstan_options(auto_write = TRUE) #which allows you to automatically save a bare version of a compiled Stan program to the hard disk so that it does not need to be recompiled (unless you change it): https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started
suppressMessages(library('loo'))   # for calculating looic and waic
suppressMessages(library('data.table')) # to read data as data.table rather than data.frame.
suppressMessages(library('bayesplot')) # to plot various figures for model checking
suppressMessages(library('R.matlab')) # to save out .mat files
suppressMessages(library('hypr')) # transfer hypothesis matrix to contrast matrix.


#The following functions are adapted from the hBayesDM package (Ahn et al., 2017): Ahn, W. Y., Haines, N., & Zhang, L. (2017). Revealing neurocomputational mechanisms of reinforcement learning and decision-making with the hBayesDM package. Computational Psychiatry, 1, 24.
source('./supp_funcs/prepro.R') #preparing the data for the stan:                         change for each project: IMPORTANT!!!!!!!!!!!!!!!!!
source('./supp_funcs/extract_ic.R') #extract looic and waic of the model:                 no chnage needed
source('./supp_funcs/printfit.R') #print looic and waic of the model and their weights:   no change needed

options(max.print = 99999) # for ploting all results of fitted model
```


1. load the csv data.
```{r}
raw_data                     <- fread(file='all_data.csv') #load as data.table: https://digitaschools.com/read-csv-in-r-importing-data/
data_df                      <- raw_data
```


2. data describing.
```{r}
# 1. Target variable: (1) choice_category: 1,2,3,4, corresponding to 0,2,4,6
# 2. Predictor variable:  (1) xd (money to the proposer); (2)xv(money to participants/agents).
# 3. supporting variables: subid (n=27), trial(1:80),cond(1=amb;2=ide),choice: decisions correspond to 0,2,4,or 6.
```

3. preparing data for stan
```{r data loading}

colnames_data_df <- colnames(data_df)

subjs    <- NULL   # List of unique subjects (1D)
n_subj   <- NULL   # Total number of subjects (0D)
t_subjs  <- NULL   # Number of trials per subject (2D or 1D)
t_max    <- NULL   # Maximum number of trials across all subjects (0D)

.N       <- NULL

DT_trials <- data_df[, .N, by = c('subid')] #get the number of trials for each sub, data.table

subjs     <- DT_trials$subid    # sub IDs
n_subj    <- length(subjs)      # no. of subs
t_subjs   <- DT_trials$N # number of trials for each sub
t_max     <- max(t_subjs) # maximal no. of trials across all subs.

gen_file <- 1 #whether or not generate a data file, only generating for main analysis, not for simulation analysis

general_info        <- list(subjs, n_subj, t_subjs, t_max,gen_file)
names(general_info) <- c('subjs', 'n_subj', 't_subjs', 't_max','gen_file')

data_list <- prepro_func(data_df,general_info)  # get the data ready for stan; MUST check the 'func01_prepro.R' file in the 'supp_funcs' directory!!!!!!!
```


4.1 set up model 1, ite_em
```{r set up model 1}
ncore <- 3
options(mc.cores = ncore) #adapted from hBayesDM_model.R
rstan_options(javascript=FALSE) # see also: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/6

#model 1, the egocentric equality model (EM). Three parameters: alpha, beta, and tau
pars_em <- c('mu_alpha','mu_tau','sigma','alpha','tau','log_lik')
fit_em <- stan(file=paste0(getwd(),'/stan_model/m01_ite_em.stan'), data=data_list,
                             pars    = pars_em,
                             chains  = 3,
                             iter    = 4000,
                             warmup  = 2000,
                             thin    = 1,
                             control = list(adapt_delta   = 0.99,
                                            stepsize      = 1,
                                            max_treedepth = 18))

save(fit_em,file='./stan_output/fit_em.RData')
printFit(fit_em,ic='both')
```




4.2 set up model 2, ite_im_mp
```{r set up model 2}
ncore <- 3
options(mc.cores = ncore) #adapted from hBayesDM_model.R
rstan_options(javascript=FALSE) # see also: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/6

#model 2, the  The impartial model,multiplicative version. Three parameters: alpha_a, alpha_i, and tau
pars_im_mp <- c('mu_alpha_a','mu_alpha_i','mu_tau','sigma','alpha_a','alpha_i','tau','log_lik')
fit_im_mp <- stan(file=paste0(getwd(),'/stan_model/m02_ite_im_mp.stan'), data=data_list,
                             pars    = pars_im_mp,
                             chains  = 3,
                             iter    = 4000,
                             warmup  = 2000,
                             thin    = 1,
                             control = list(adapt_delta   = 0.99,
                                            stepsize      = 1,
                                            max_treedepth = 18))

save(fit_im_mp,file='./stan_output/fit_im_mp.RData')
printFit(fit_im_mp,ic='both')

```



4.3 set up model 3, ite_im_ad
```{r set up model 3}
ncore <- 3
options(mc.cores = ncore) #adapted from hBayesDM_model.R
rstan_options(javascript=FALSE) # see also: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/6

#model 3, the  The impartial model,additive version. Four parameters: alpha, omega_a, omega_i, and tau
pars_im_ad <- c('mu_alpha','mu_omega_a','mu_omega_i','mu_tau','sigma','alpha','omega_a','omega_i','tau','log_lik')
fit_im_ad <- stan(file=paste0(getwd(),'/stan_model/m03_ite_im_ad.stan'), data=data_list,
                             pars    = pars_im_ad,
                             chains  = 3,
                             iter    = 4000,
                             warmup  = 2000,
                             thin    = 1,
                             control = list(adapt_delta   = 0.99,
                                            stepsize      = 1,
                                            max_treedepth = 18))

save(fit_im_ad,file='./stan_output/fit_im_ad.RData')
printFit(fit_im_ad,ic='both')

```



4.4 set up model 4, ite_vm_mp
```{r set up model 4}
ncore <- 3
options(mc.cores = ncore) #adapted from hBayesDM_model.R
rstan_options(javascript=FALSE) # see also: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/6

#model 4, the  The vicarious model,multiplicative version. Three parameters: alpha_a, alpha_i, and tau
pars_vm_mp <- c('mu_alpha_a','mu_alpha_i','mu_tau','sigma','alpha_a','alpha_i','tau','log_lik')
fit_vm_mp <- stan(file=paste0(getwd(),'/stan_model/m04_ite_vm_mp.stan'), data=data_list,
                             pars    = pars_vm_mp,
                             chains  = 3,
                             iter    = 4000,
                             warmup  = 2000,
                             thin    = 1,
                             control = list(adapt_delta   = 0.99,
                                            stepsize      = 1,
                                            max_treedepth = 18))

save(fit_vm_mp,file='./stan_output/fit_vm_mp.RData')
printFit(fit_vm_mp,ic='both')

```



4.5 set up model 5, ite_vm_ad
```{r set up model 5}
ncore <- 3
options(mc.cores = ncore) #adapted from hBayesDM_model.R
rstan_options(javascript=FALSE) # see also: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/6

#model 5, the  The vicarious model,additive version. Four parameters: alpha, omega_a, omega_i, and tau
pars_vm_ad <- c('mu_alpha','mu_omega_a','mu_omega_i','mu_tau','sigma','alpha','omega_a','omega_i','tau','log_lik')
fit_vm_ad <- stan(file=paste0(getwd(),'/stan_model/m05_ite_vm_ad.stan'), data=data_list,
                             pars    = pars_vm_ad,
                             chains  = 3,
                             iter    = 4000,
                             warmup  = 2000,
                             thin    = 1,
                             control = list(adapt_delta   = 0.99,
                                            stepsize      = 1,
                                            max_treedepth = 18))

save(fit_vm_ad,file='./stan_output/fit_vm_ad.RData')
printFit(fit_vm_ad,ic='both')


###########################################################################individual paramters#######################################################################
# Extract from the Stan fit object
parVals <- rstan::extract(fit_vm_ad, permuted = TRUE)

# Define measurement of individual parameters
indPars <- "mean" #extracting mean of parameters
measure_indPars <- switch(indPars, mean = mean, median = median, mode = estimate_mode)
which_indPars <- c('alpha','omega_a','omega_i','tau') #vectors

multp_which_indPars <- NULL  # matrix

# Measure all individual parameters (per subject)
allIndPars <- as.data.frame(array(NA, c(n_subj, length(which_indPars))))
m_allIndPars <- as.data.frame(array(NA, c(n_subj, 50))) #'50' here is an arbitrary value, just to make sure that the number of parameters are below this value.
m_names  <- rep(NULL,50)
for (i in 1:n_subj) {
  
  allIndPars[i, ] <- mapply(function(x) measure_indPars(parVals[[x]][, i]), which_indPars)
  
  if (length(multp_which_indPars)>0){  # for parameters in the matrix form
    count <-0
    for (nm in 1: length(multp_which_indPars)){
      for (ds in 1:dim(parVals[[multp_which_indPars[nm]]])[3]){
        count <- count + 1
        m_allIndPars[i, count] <- sapply(list(parVals[[multp_which_indPars[nm]]][, i,ds]),function(x) measure_indPars(x))
        m_names[count] <- paste0(multp_which_indPars[nm],ds)
      }
    }
  }
}

if (length(multp_which_indPars)>0){
  m_allIndPars <- m_allIndPars[,1:count]
  m_allIndPars <- as.data.frame(m_allIndPars)
  m_names      <- m_names[1:count]
  
  allIndPars <- cbind(subjs, allIndPars,m_allIndPars)
  colnames(allIndPars) <- c("subjid", which_indPars,m_names)
} else {
  allIndPars <- cbind(subjs, allIndPars)
  colnames(allIndPars) <- c("subjid", which_indPars) 
}


write.csv(allIndPars,file='IndPars_fit_vm_ad.csv',row.names = FALSE)

```




4.5 set up model 5, ite_vm_ad2, using a even weaker informative priors
```{r set up model 5}
ncore <- 3
options(mc.cores = ncore) #adapted from hBayesDM_model.R
rstan_options(javascript=FALSE) # see also: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/6

#model 5, the  The vicarious model,additive version. Four parameters: alpha, omega_a, omega_i, and tau
pars_vm_ad2 <- c('mu_alpha','mu_omega_a','mu_omega_i','mu_tau','sigma','alpha','omega_a','omega_i','tau','log_lik')
fit_vm_ad2 <- stan(file=paste0(getwd(),'/stan_model/m05_ite_vm_ad2.stan'), data=data_list,
                             pars    = pars_vm_ad2,
                             chains  = 3,
                             iter    = 4000,
                             warmup  = 2000,
                             thin    = 1,
                             control = list(adapt_delta   = 0.99,
                                            stepsize      = 1,
                                            max_treedepth = 18))

save(fit_vm_ad2,file='./stan_output/fit_vm_ad2.RData')
printFit(fit_vm_ad2,ic='both')

###########################################################################individual paramters#######################################################################
# Extract from the Stan fit object
parVals <- rstan::extract(fit_vm_ad2, permuted = TRUE)

# Define measurement of individual parameters
indPars <- "mean" #extracting mean of parameters
measure_indPars <- switch(indPars, mean = mean, median = median, mode = estimate_mode)
which_indPars <- c('alpha','omega_a','omega_i','tau') #vectors

multp_which_indPars <- NULL  # matrix

# Measure all individual parameters (per subject)
allIndPars <- as.data.frame(array(NA, c(n_subj, length(which_indPars))))
m_allIndPars <- as.data.frame(array(NA, c(n_subj, 50))) #'50' here is an arbitrary value, just to make sure that the number of parameters are below this value.
m_names  <- rep(NULL,50)
for (i in 1:n_subj) {
  
  allIndPars[i, ] <- mapply(function(x) measure_indPars(parVals[[x]][, i]), which_indPars)
  
  if (length(multp_which_indPars)>0){  # for parameters in the matrix form
    count <-0
    for (nm in 1: length(multp_which_indPars)){
      for (ds in 1:dim(parVals[[multp_which_indPars[nm]]])[3]){
        count <- count + 1
        m_allIndPars[i, count] <- sapply(list(parVals[[multp_which_indPars[nm]]][, i,ds]),function(x) measure_indPars(x))
        m_names[count] <- paste0(multp_which_indPars[nm],ds)
      }
    }
  }
}

if (length(multp_which_indPars)>0){
  m_allIndPars <- m_allIndPars[,1:count]
  m_allIndPars <- as.data.frame(m_allIndPars)
  m_names      <- m_names[1:count]
  
  allIndPars <- cbind(subjs, allIndPars,m_allIndPars)
  colnames(allIndPars) <- c("subjid", which_indPars,m_names)
} else {
  allIndPars <- cbind(subjs, allIndPars)
  colnames(allIndPars) <- c("subjid", which_indPars) 
}


write.csv(allIndPars,file='IndPars_fit_vm_ad2.csv',row.names = FALSE)

```




